### ISSUE TITLE
Exclude files from distribution

### ISSUE THREAD

**Issue by bytestream** [googleapis/common-protos-php#17]
Will you accept a PR which excludes `dev/` and `tests/` from distribution via `.gitattributes`? See https://php.watch/articles/composer-gitattributes for more information on excluding files.

Are there any other files / directories which should not be distributed?

**Comment by dwsupplee** [comment]
@bytestream that would be great, those two directories would be good. Thank you!

**Comment by bytestream** [comment]
@dwsupplee no worries - https://github.com/googleapis/common-protos-php/pull/18
