### ISSUE TITLE
Protobuf requirement downgraded from v4.7.0 to v4.8.x

### ISSUE THREAD

**Issue by andreladocruz** [googleapis/common-protos-php#92]
On version v4.7.0 the required protobuf version was 

`
 "require": {
    "php": "^8.0",
    "google/protobuf": "^v3.25.3||^4.26.1"
  },
`

On version v4.8.X is:

`
 "require": {
    "php": "^8.0",
    "google/protobuf": "^3.6.1"
  },
`

Could you explain why?

**Comment by Hectorhammett** [comment]
Hello @andreladocruz!

Thanks for the message, yeah it seems that there is a bug related to this, will take a look and figure out what happened. Will keep you posted!

**Comment by andreladocruz** [comment]
thanks, @Hectorhammett =) =) =)

**Comment by bshaffer** [comment]
Thank you for finding this issue, @andreladocruz ! This will be released later today in version `4.8.3`
